In [2]:
import pandas as pd

data=pd.read_csv(r"C:\Users\SUDHA\Downloads\nba.csv")

In [6]:
data

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
...,...,...,...,...,...,...,...,...,...
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
grouped_data = data.groupby('Team')
grouped_data.first()

,Name,Number,Position,Age,Height,Weight,College,Salary
Team,,,,,,,,
Atlanta Hawks,Kent Bazemore,24.0,SF,26.0,6-5,201.0,Old Dominion,2000000.0
Boston Celtics,Avery Bradley,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
Brooklyn Nets,Bojan Bogdanovic,44.0,SG,27.0,6-8,216.0,Oklahoma State,3425510.0
Charlotte Hornets,Nicolas Batum,5.0,SG,27.0,6-8,200.0,Virginia Commonwealth,13125306.0
Chicago Bulls,Cameron Bairstow,41.0,PF,25.0,6-9,250.0,New Mexico,845059.0
Cleveland Cavaliers,Matthew Dellavedova,8.0,PG,25.0,6-4,198.0,Saint Mary's,1147276.0
Dallas Mavericks,Justin Anderson,1.0,SG,22.0,6-6,228.0,Virginia,1449000.0
Denver Nuggets,Darrell Arthur,0.0,PF,28.0,6-9,235.0,Kansas,2814000.0
Detroit Pistons,Joel Anthony,50.0,C,33.0,6-9,245.0,UNLV,2500000.0
Golden State Warriors,Leandro Barbosa,19.0,SG,33.0,6-3,194.0,North Carolina,2500000.0
Houston Rockets,Trevor Ariza,1.0,SF,30.0,6-8,215.0,UCLA,8193030.0
Indiana Pacers,Lavoy Allen,5.0,PF,27.0,6-9,255.0,Temple,4050000.0
Los Angeles Clippers,Cole Aldrich,45.0,C,27.0,6-11,250.0,Kansas,1100602.0
Los Angeles Lakers,Brandon Bass,2.0,PF,31.0,6-8,250.0,LSU,3000000.0
Memphis Grizzlies,Jordan Adams,3.0,SG,21.0,6-5,209.0,UCLA,1404600.0
Miami Heat,Chris Bosh,1.0,PF,32.0,6-11,235.0,Georgia Tech,22192730.0
Milwaukee Bucks,Giannis Antetokounmpo,34.0,SF,21.0,6-11,222.0,Arizona,1953960.0
Minnesota Timberwolves,Nemanja Bjelica,88.0,PF,28.0,6-10,240.0,Louisville,3950001.0
New Orleans Pelicans,Alexis Ajinca,42.0,C,28.0,7-2,248.0,California,4389607.0
New York Knicks,Arron Afflalo,4.0,SG,30.0,6-5,210.0,UCLA,8000000.0
Oklahoma City Thunder,Steven Adams,12.0,C,22.0,7-0,255.0,Pittsburgh,2279040.0
Orlando Magic,Dewayne Dedmon,3.0,C,26.0,7-0,245.0,USC,947276.0
Philadelphia 76ers,Elton Brand,42.0,PF,37.0,6-9,254.0,Duke,947276.0
Phoenix Suns,Eric Bledsoe,2.0,PG,26.0,6-1,190.0,Kentucky,13500000.0
Portland Trail Blazers,Cliff Alexander,34.0,PF,20.0,6-8,240.0,Kansas,525093.0
Sacramento Kings,Quincy Acy,13.0,SF,25.0,6-7,240.0,Baylor,981348.0
San Antonio Spurs,LaMarcus Aldridge,12.0,PF,30.0,6-11,240.0,Texas,19689000.0
Toronto Raptors,Bismack Biyombo,8.0,C,23.0,6-9,245.0,Missouri,2814000.0
Utah Jazz,Trevor Booker,33.0,PF,28.0,6-8,228.0,Clemson,4775000.0
Washington Wizards,Alan Anderson,6.0,SG,33.0,6-6,220.0,Michigan State,4000000.0

In [7]:
grouped_data.get_group("Charlotte Hornets")

,Name,Number,Position,Age,Height,Weight,College,Salary
324,Nicolas Batum,5.0,SG,27.0,6-8,200.0,NaN,13125306.0
325,Troy Daniels,30.0,SG,24.0,6-4,205.0,Virginia Commonwealth,947276.0
326,Jorge Gutierrez,12.0,PG,27.0,6-3,189.0,California,189455.0
327,Tyler Hansbrough,50.0,PF,30.0,6-9,250.0,North Carolina,947276.0
328,Aaron Harrison,9.0,SG,21.0,6-6,210.0,Kentucky,525093.0
329,Spencer Hawes,0.0,PF,28.0,7-1,245.0,Washington,6110034.0
330,Al Jefferson,25.0,C,31.0,6-10,289.0,NaN,13500000.0
331,Frank Kaminsky III,44.0,C,23.0,7-0,240.0,Wisconsin,2612520.0
332,Michael Kidd-Gilchrist,14.0,SF,22.0,6-7,232.0,Kentucky,6331404.0
333,Jeremy Lamb,3.0,SG,24.0,6-5,185.0,Connecticut,3034356.0
334,Courtney Lee,1.0,SG,30.0,6-5,200.0,Western Kentucky,5675000.0
335,Jeremy Lin,7.0,PG,27.0,6-3,200.0,Harvard,2139000.0
336,Kemba Walker,15.0,PG,26.0,6-1,184.0,Connecticut,12000000.0
337,Marvin Williams,2.0,PF,29.0,6-9,237.0,North Carolina,7000000.0
338,Cody Zeller,40.0,C,23.0,7-0,240.0,Indiana,4204200.0

In [9]:
data.groupby('Team')[['Salary','Age']].agg({'Salary':['mean','sum'], 'Age':['max','min']})

                              Salary                Age
                                mean          sum   max   min
Team
Atlanta Hawks           4.860197e+06   72902950.0  35.0  22.0
Boston Celtics          4.181505e+06   58541068.0  29.0  20.0
Brooklyn Nets           3.501898e+06   52528475.0  32.0  21.0
Charlotte Hornets       5.222728e+06   78340920.0  31.0  21.0
Chicago Bulls           5.785559e+06   86783378.0  35.0  21.0
Cleveland Cavaliers     7.642049e+06  106988689.0  35.0  24.0
Dallas Mavericks        4.746582e+06   71198732.0  37.0  22.0
Denver Nuggets          4.294424e+06   60121930.0  36.0  20.0
Detroit Pistons         4.477884e+06   67168263.0  36.0  20.0
Golden State Warriors   5.924600e+06   88868997.0  33.0  20.0
Houston Rockets         5.018868e+06   75283021.0  38.0  22.0
Indiana Pacers          4.450122e+06   66751826.0  30.0  20.0
Los Angeles Clippers    6.323643e+06   94854640.0  39.0  23.0
Los Angeles Lakers      4.784695e+06   71770431.0  37.0  20.0
Memphis Grizzlies       5.467920e+06   76550880.0  39.0  21.0
Miami Heat              6.347359e+06   82515673.0  36.0  20.0
Milwaukee Bucks         4.350220e+06   69603517.0  32.0  19.0
Minnesota Timberwolves  4.593054e+06   59709697.0  40.0  20.0
New Orleans Pelicans    4.355304e+06   82750774.0  31.0  23.0
New York Knicks         4.581494e+06   73303898.0  34.0  20.0
Oklahoma City Thunder   6.251020e+06   93765298.0  38.0  21.0
Orlando Magic           4.297248e+06   60161470.0  32.0  20.0
Philadelphia 76ers      2.213778e+06   30992894.0  37.0  20.0
Phoenix Suns            4.229676e+06   63445135.0  33.0  19.0
Portland Trail Blazers  3.220121e+06   48301818.0  34.0  20.0
Sacramento Kings        4.778911e+06   71683666.0  36.0  22.0
San Antonio Spurs       5.629516e+06   84442733.0  40.0  22.0
Toronto Raptors         4.741174e+06   71117611.0  36.0  20.0
Utah Jazz               4.204006e+06   63060091.0  28.0  20.0
Washington Wizards      5.088576e+06   76328636.0  34.0  20.0